export const dict = {
  de: {
    common: {
      brand: "Brand Guidelines",
      themeToggleLight: "Hellmodus",
      themeToggleDark: "Dunkelmodus",
      langSwitch: "Sprache wechseln",
      skipToContent: "Zum Inhalt springen",
    },
    nav: {
      logo: "Logo",
      farben: "Farben",
      typografie: "Typografie",
      bildsprache: "Bildsprache",
      anwendungen: "Anwendungen",
      downloads: "Downloads",
    },
    hero: {
      eyebrow: "Brand Guidelines · 2026",
      line1: "Für Beauty.",
      line2: "Für Health.",
      line3: "Für alle, die formulieren.",
      lead: "Dieses Brand-Book bündelt alle Bausteine der visuellen Identität von SLI Chemicals — Logo, Farben, Typografie, Bildsprache und Anwendungsbeispiele. Es richtet sich an alle, die unsere Marke in digitalen und gedruckten Medien sichtbar machen.",
      metaPre: "Stand: Mai 2026. Bei Fragen zur Anwendung wenden Sie sich bitte an ",
    },
    toc: {
      eyebrow: "Inhalt",
      heading: "Sechs Kapitel.",
      lead: "Springen Sie direkt zu den Themen, die Sie für Ihr Projekt brauchen.",
      items: [
        { no: "01", id: "logo",        title: "Logo",        note: "Wortbildmarke, Schutzraum, Anwendung" },
        { no: "02", id: "farben",      title: "Farben",      note: "Primär- und Sekundärpalette, Tokens" },
        { no: "03", id: "typografie",  title: "Typografie",  note: "Helvetica · Display & Body" },
        { no: "04", id: "bildsprache", title: "Bildsprache", note: "Editorial · Brand Cover · Lifestyle" },
        { no: "05", id: "anwendungen", title: "Anwendungen", note: "Print, Web, Messeauftritt" },
        { no: "06", id: "downloads",   title: "Downloads",   note: "Logo-Pack, Tokens, Templates" },
      ],
    },
    logo: {
      eyebrow: "Wortbildmarke",
      title: "Das Logo",
      lead: "Die SLI-Wortbildmarke ist der zentrale Identifikator unserer Marke. Sie wird stets ohne Modifikation verwendet — kein Verzerren, kein Neufärben, kein Hinzufügen von Effekten.",
      altLight: "SLI Chemicals Logo auf hellem Hintergrund",
      altBrand: "SLI Chemicals Logo auf Markenfarbe",
      rules: [
        { label: "Schutzraum",   text: "Mindestens die Höhe des Buchstabens „S“ als Freiraum auf allen Seiten." },
        { label: "Mindestgröße", text: "Print: 24 mm Breite · Digital: 120 px Breite — kleiner wird die Lesbarkeit beeinträchtigt." },
        { label: "Hintergrund",  text: "Auf hellen Flächen Originalfarbe, auf dunklen oder Markenfarbe ausschließlich weiß." },
      ],
    },
    color: {
      eyebrow: "Farbsystem",
      title: "Farben",
      lead: "Das SLI Green ist das Herz unserer Marke. Es trägt jede Anwendung und steht für unsere Wurzeln in Natur, Nachhaltigkeit und Forschung. Sekundärfarben und Neutrals strukturieren das Layout, ohne die Primärfarbe zu konkurrenzieren.",
      primaryEyebrow: "Primär · 01",
      primaryName: "SLI Green",
      secondary: [
        { name: "Deep Green", hex: "#004A30", note: "Hover / Text auf hellem Grund" },
        { name: "Mid Green",  hex: "#2E8C63", note: "Akzente, Highlights" },
        { name: "Soft Mint",  hex: "#D6E8DF", note: "Flächen, Karten-Hintergrund" },
      ],
      neutralsHeading: "Neutrals",
      neutralsLead: "Für Text, Flächen und Trennlinien",
      neutrals: [
        { name: "Ink",        hex: "#0F120F", note: "Primäre Textfarbe" },
        { name: "Ink Soft",   hex: "#2B2E2B", note: "Sekundärer Text" },
        { name: "Ink Muted",  hex: "#6A6F68", note: "Hilfstext, Captions" },
        { name: "Line",       hex: "#E2DFD6", note: "Trennlinien" },
        { name: "Paper",      hex: "#F6F4EE", note: "Hintergrund" },
        { name: "Paper Soft", hex: "#EFECE3", note: "Sekundärer Hintergrund" },
      ],
      a11yEyebrow: "Zugänglichkeit",
      a11yText: "SLI Green auf Weiß erreicht ein Kontrastverhältnis von 8.4:1 — WCAG AAA für alle Textgrößen. Für Text auf SLI Green nutzen Sie ausschließlich Weiß oder Paper, niemals Ink.",
    },
    typo: {
      eyebrow: "Schrift",
      title: "Typografie",
      lead: "Helvetica ist die Stimme der Marke — neutral, präzise, international lesbar. Sie spiegelt unsere wissenschaftliche Haltung wider, ohne distanziert zu wirken.",
      faceEyebrow: "Haupt-Schrift · seit 2026",
      faceLead: "System-sicher, weltweit verfügbar — Helvetica Neue mit Fallback auf Arial. Web-Stack:",
      scaleHeading: "Typ-Skala",
      scaleLead: "Konsistente Hierarchie über alle Touchpoints",
      scale: [
        { name: "Display",   size: "96px", weight: "Medium",  sample: "Specialty." },
        { name: "H1",        size: "64px", weight: "Medium",  sample: "Brand Guidelines" },
        { name: "H2",        size: "40px", weight: "Medium",  sample: "Our color system" },
        { name: "H3",        size: "24px", weight: "Medium",  sample: "Personal Care" },
        { name: "Body Lead", size: "18px", weight: "Regular", sample: "Your partner in formulation." },
        { name: "Body",      size: "16px", weight: "Regular", sample: "Specialty chemicals and natural raw materials." },
        { name: "Caption",   size: "12px", weight: "Regular", sample: "Stand: Mai 2026" },
      ],
      weights: [
        { w: 300, name: "Light" },
        { w: 400, name: "Regular" },
        { w: 500, name: "Medium" },
        { w: 700, name: "Bold" },
      ],
    },
    imagery: {
      eyebrow: "Bildwelt",
      title: "Bildsprache",
      lead: "Bilder bei SLI sind nie Dekoration. Sie zeigen Anwendung, Wirkung und Werte. Drei Bildtypen begleiten uns über alle Touchpoints — Editorial, Brand Cover und Lifestyle.",
      themes: [
        { title: "Editorial",   badge: "Skin Care Ingredients",  description: "Hochwertig inszenierte Aufnahmen für Cover-Motive und Print-Herobilder. Klare Bildachse, ein Hauptmotiv, kontrolliertes Licht." },
        { title: "Brand Cover", badge: "Cosmetic Ingredients",   description: "Broschüren- und Präsentationstitel. Logo oben rechts, Markenfarbe als Akzent, dezenter Textblock unter dem Motiv." },
        { title: "Lifestyle",   badge: "Sustainability",         description: "Authentische Porträts mit natürlichem Licht. Anwendungsnah, ohne Stockfoto-Klischee — zeigt den Menschen vor dem Produkt." },
      ],
      doHeading: "So machen wir es",
      doList: [
        "Authentische Materialien, echte Texturen",
        "Natürliches Licht, warme Schatten",
        "Eine klare Bildaussage pro Aufnahme",
        "Logo oben rechts, Markenfarbe als Akzent",
      ],
      dontHeading: "Vermeiden",
      dontList: [
        "Generische Stock-Lab-Coats und Reagenzgläser",
        "Übersättigte oder kühl-blaue Tonalität",
        "Collagen aus mehreren Motiven",
        "Text-im-Bild ohne klaren Zweck",
      ],
    },
    applications: {
      eyebrow: "Touchpoints",
      title: "Anwendungen",
      lead: "Die Bausteine in Aktion: Logo, Farbe und Typografie wirken nur, wenn sie konsistent über alle Medien getragen werden. Hier eine Auswahl typischer Touchpoints.",
      cardName: "Maria Müller",
      cardRole: "Application Specialist",
      webHeadline1: "Specialty Chemicals",
      webHeadline2: "for tomorrow.",
      webCta: "Mehr erfahren",
      tradeEyebrow: "Messe-Auftritt",
      tradeHeadline1: "See you at",
      tradeHeadline2: "in-cosmetics 2026.",
    },
    downloads: {
      eyebrow: "Asset-Pakete",
      title: "Downloads",
      lead: "Alles, was Sie zur Umsetzung brauchen — geprüft, freigegeben, in den richtigen Formaten. Bitte ausschließlich diese Dateien verwenden.",
      packs: [
        { title: "Logo-Pack",        desc: "Wortbildmarke in SVG, PNG und EPS — alle Varianten und Negativ-Versionen.",           format: "ZIP · 4 MB"  },
        { title: "Farb-Tokens",      desc: "Hex, RGB, CMYK und Pantone-Werte als CSS, JSON und ASE-Swatch-Datei.",                 format: "ZIP · 28 KB" },
        { title: "Office-Templates", desc: "Briefbogen, Präsentation, E-Mail-Signatur — direkt einsetzbar in MS Office.",          format: "ZIP · 6 MB"  },
        { title: "Brand-Buch (PDF)", desc: "Diese komplette Übersicht als druckfähiges PDF zum Teilen.",                            format: "PDF · 12 MB" },
      ],
      contactEyebrow: "Fragen zur Anwendung?",
      contactHeading: "Sprechen Sie mit dem Marketing-Team.",
      contactLead: "Wir prüfen Layouts, beraten zu Sonderfällen und liefern individuelle Asset-Anpassungen, wenn die Standard-Pakete nicht ausreichen.",
    },
    footer: {
      tagline: "Your Partner for Specialty Chemicals and Natural Raw Materials in Beauty, Health, and Pet Food.",
      portalHeading: "Brand Portal",
      portalLinks: [
        { href: "#downloads",  label: "Logo & Asset Downloads" },
        { href: "#farben",     label: "Farb-Tokens" },
        { href: "#anwendungen", label: "Anwendungsbeispiele" },
      ],
      contactHeading: "Kontakt",
      version: "Brand Guidelines · v1.0",
      copyright: (year) => `© ${year} SLI Chemicals. Alle Rechte vorbehalten.`,
    },
  },

  en: {
    common: {
      brand: "Brand Guidelines",
      themeToggleLight: "Light mode",
      themeToggleDark: "Dark mode",
      langSwitch: "Switch language",
      skipToContent: "Skip to content",
    },
    nav: {
      logo: "Logo",
      farben: "Colors",
      typografie: "Typography",
      bildsprache: "Imagery",
      anwendungen: "Applications",
      downloads: "Downloads",
    },
    hero: {
      eyebrow: "Brand Guidelines · 2026",
      line1: "For beauty.",
      line2: "For health.",
      line3: "For everyone who formulates.",
      lead: "This brand book brings together every building block of SLI Chemicals' visual identity — logo, colors, typography, imagery and application examples. It is meant for everyone who carries our brand into digital and printed media.",
      metaPre: "Last updated: May 2026. For questions about usage please reach out to ",
    },
    toc: {
      eyebrow: "Contents",
      heading: "Six chapters.",
      lead: "Jump straight to the topics you need for your project.",
      items: [
        { no: "01", id: "logo",        title: "Logo",        note: "Wordmark, clear space, usage" },
        { no: "02", id: "farben",      title: "Colors",      note: "Primary & secondary palette, tokens" },
        { no: "03", id: "typografie",  title: "Typography",  note: "Helvetica · Display & Body" },
        { no: "04", id: "bildsprache", title: "Imagery",     note: "Editorial · Brand Cover · Lifestyle" },
        { no: "05", id: "anwendungen", title: "Applications", note: "Print, web, trade-show" },
        { no: "06", id: "downloads",   title: "Downloads",   note: "Logo pack, tokens, templates" },
      ],
    },
    logo: {
      eyebrow: "Wordmark",
      title: "The Logo",
      lead: "The SLI wordmark is the central identifier of our brand. It is always used without modification — no distortion, no recoloring, no added effects.",
      altLight: "SLI Chemicals logo on light background",
      altBrand: "SLI Chemicals logo on brand color",
      rules: [
        { label: "Clear space",   text: "At least the height of the letter “S” as free space on all sides." },
        { label: "Minimum size",  text: "Print: 24 mm wide · Digital: 120 px wide — smaller hurts legibility." },
        { label: "Background",    text: "On light surfaces original color, on dark or brand color use white only." },
      ],
    },
    color: {
      eyebrow: "Color system",
      title: "Colors",
      lead: "SLI Green is the heart of our brand. It carries every application and stands for our roots in nature, sustainability and research. Secondary colors and neutrals structure the layout without competing with the primary color.",
      primaryEyebrow: "Primary · 01",
      primaryName: "SLI Green",
      secondary: [
        { name: "Deep Green", hex: "#004A30", note: "Hover / text on light" },
        { name: "Mid Green",  hex: "#2E8C63", note: "Accents, highlights" },
        { name: "Soft Mint",  hex: "#D6E8DF", note: "Surfaces, card backgrounds" },
      ],
      neutralsHeading: "Neutrals",
      neutralsLead: "For text, surfaces and dividers",
      neutrals: [
        { name: "Ink",        hex: "#0F120F", note: "Primary text color" },
        { name: "Ink Soft",   hex: "#2B2E2B", note: "Secondary text" },
        { name: "Ink Muted",  hex: "#6A6F68", note: "Helper text, captions" },
        { name: "Line",       hex: "#E2DFD6", note: "Dividers" },
        { name: "Paper",      hex: "#F6F4EE", note: "Background" },
        { name: "Paper Soft", hex: "#EFECE3", note: "Secondary background" },
      ],
      a11yEyebrow: "Accessibility",
      a11yText: "SLI Green on white reaches a contrast ratio of 8.4:1 — WCAG AAA for all text sizes. For text on SLI Green use white or paper only, never ink.",
    },
    typo: {
      eyebrow: "Type",
      title: "Typography",
      lead: "Helvetica is the voice of the brand — neutral, precise, legible internationally. It reflects our scientific posture without coming across as distant.",
      faceEyebrow: "Primary typeface · since 2026",
      faceLead: "System-safe, globally available — Helvetica Neue with Arial as fallback. Web stack:",
      scaleHeading: "Type scale",
      scaleLead: "Consistent hierarchy across every touchpoint",
      scale: [
        { name: "Display",   size: "96px", weight: "Medium",  sample: "Specialty." },
        { name: "H1",        size: "64px", weight: "Medium",  sample: "Brand Guidelines" },
        { name: "H2",        size: "40px", weight: "Medium",  sample: "Our color system" },
        { name: "H3",        size: "24px", weight: "Medium",  sample: "Personal Care" },
        { name: "Body Lead", size: "18px", weight: "Regular", sample: "Your partner in formulation." },
        { name: "Body",      size: "16px", weight: "Regular", sample: "Specialty chemicals and natural raw materials." },
        { name: "Caption",   size: "12px", weight: "Regular", sample: "Updated: May 2026" },
      ],
      weights: [
        { w: 300, name: "Light" },
        { w: 400, name: "Regular" },
        { w: 500, name: "Medium" },
        { w: 700, name: "Bold" },
      ],
    },
    imagery: {
      eyebrow: "Visual world",
      title: "Imagery",
      lead: "At SLI, images are never decoration. They show application, effect and values. Three image types accompany us across every touchpoint — Editorial, Brand Cover and Lifestyle.",
      themes: [
        { title: "Editorial",   badge: "Skin Care Ingredients", description: "Polished, staged photography for cover motifs and print heroes. Clear visual axis, one main subject, controlled lighting." },
        { title: "Brand Cover", badge: "Cosmetic Ingredients",  description: "Brochure and presentation covers. Logo top right, brand color as accent, a quiet text block under the motif." },
        { title: "Lifestyle",   badge: "Sustainability",        description: "Authentic portraits in natural light. Close to usage, free of stock clichés — shows the person before the product." },
      ],
      doHeading: "Do",
      doList: [
        "Authentic materials, real textures",
        "Natural light, warm shadows",
        "One clear message per shot",
        "Logo top right, brand color as accent",
      ],
      dontHeading: "Avoid",
      dontList: [
        "Generic stock lab coats and test tubes",
        "Oversaturated or cool-blue tonality",
        "Collages of multiple motifs",
        "Text-in-image without clear purpose",
      ],
    },
    applications: {
      eyebrow: "Touchpoints",
      title: "Applications",
      lead: "The building blocks in action: logo, color and type only work if they are carried consistently across every medium. A selection of typical touchpoints.",
      cardName: "Maria Müller",
      cardRole: "Application Specialist",
      webHeadline1: "Specialty Chemicals",
      webHeadline2: "for tomorrow.",
      webCta: "Learn more",
      tradeEyebrow: "Trade-show",
      tradeHeadline1: "See you at",
      tradeHeadline2: "in-cosmetics 2026.",
    },
    downloads: {
      eyebrow: "Asset packs",
      title: "Downloads",
      lead: "Everything you need to ship — reviewed, approved, in the right formats. Please use these files only.",
      packs: [
        { title: "Logo pack",        desc: "Wordmark in SVG, PNG and EPS — every variant and negative.",                       format: "ZIP · 4 MB"  },
        { title: "Color tokens",     desc: "Hex, RGB, CMYK and Pantone values as CSS, JSON and an ASE swatch file.",            format: "ZIP · 28 KB" },
        { title: "Office templates", desc: "Letter, presentation, email signature — drop-in ready for MS Office.",              format: "ZIP · 6 MB"  },
        { title: "Brand book (PDF)", desc: "This complete overview as a print-ready PDF for sharing.",                          format: "PDF · 12 MB" },
      ],
      contactEyebrow: "Questions about usage?",
      contactHeading: "Talk to the marketing team.",
      contactLead: "We review layouts, advise on special cases and deliver custom asset adaptations when the standard packs are not enough.",
    },
    footer: {
      tagline: "Your Partner for Specialty Chemicals and Natural Raw Materials in Beauty, Health, and Pet Food.",
      portalHeading: "Brand Portal",
      portalLinks: [
        { href: "#downloads",   label: "Logo & asset downloads" },
        { href: "#farben",      label: "Color tokens" },
        { href: "#anwendungen", label: "Application examples" },
      ],
      contactHeading: "Contact",
      version: "Brand Guidelines · v1.0",
      copyright: (year) => `© ${year} SLI Chemicals. All rights reserved.`,
    },
  },
};
